FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

# Use legacy-peer-deps to prevent install errors in old projects
RUN npm install --legacy-peer-deps

# Optional: Install nodemon globally if you use it for dev
RUN npm install -g nodemon

COPY . .

# Ensure upload directory exists
RUN mkdir -p /app/uploads

EXPOSE 5000

CMD ["npm", "start"]