FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

# Use legacy-peer-deps to prevent install errors
RUN npm install --legacy-peer-deps

COPY . .

# Ensure upload directory exists
RUN mkdir -p /app/uploads

EXPOSE 5000

CMD ["node", "server.js"]